### ISSUE TITLE
Changing review table name

### ISSUE THREAD

**Issue by srakl** [artisanry/reviewable#28]
Getting a lot of errors, so had to do these steps to get it to work.

in my Model i had to change

`use Artisanry\Reviewable\HasReviews;` to use `Artisanry\Reviewable\Traits\HasReviews;`

in my `config/laravel-reviewable.php` i had to change

`'review' => \Artisanry\Reviewable\Review::class,` to '`review' => \Artisanry\Reviewable\Models\Review::class,`

but now I'm getting this error,

`Base table or view not found: 1146 Table 'v4_db.reviews' doesn't exist`

But now, how do i change the table name from `reviews` to `user_reviews` ?

**Comment by faustbrian** [comment]
Currently it's not possible to use a custom table name, feel free to submit a PR.
